function l12 = l12_gen(x,y,theta,R1,R2,xo,yo,d)
%L12_GEN
%    L12 = L12_GEN(X,Y,THETA,R1,R2,XO,YO,D)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Aug-2020 16:21:29

t2 = cos(theta);
t3 = sin(theta);
l12 = ((-x+xo+R1.*t3).^2+(y-yo+R1.*t2).^2-(R1+d).^2).*((x-xo+R2.*t3).^2+(-y+yo+R2.*t2).^2-(R2+d).^2);
