function l1 = l1_gen(x,y,theta,R,xo,yo,d)
%L1_GEN
%    L1 = L1_GEN(X,Y,THETA,R,XO,YO,D)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Aug-2020 22:06:19

l1 = -(R+d).^2+(y-yo+R.*cos(theta)).^2+(-x+xo+R.*sin(theta)).^2;
