function l2 = l2_gen(x,y,theta,R,xo,yo,d)
%L2_GEN
%    L2 = L2_GEN(X,Y,THETA,R,XO,YO,D)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Aug-2020 22:06:20

l2 = -(R+d).^2+(-y+yo+R.*cos(theta)).^2+(x-xo+R.*sin(theta)).^2;
