function Lfl12 = Lfl12_gen(x,y,theta,V,R1,R2,xo,yo,d)
%LFL12_GEN
%    LFL12 = LFL12_GEN(X,Y,THETA,V,R1,R2,XO,YO,D)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Aug-2020 16:20:28

t2 = cos(theta);
t3 = sin(theta);
t4 = R1+d;
t5 = R2+d;
t6 = x.*2.0;
t7 = xo.*2.0;
t8 = y.*2.0;
t9 = yo.*2.0;
t14 = -x;
t15 = -xo;
t16 = -y;
t17 = -yo;
t10 = R1.*t2;
t11 = R2.*t2;
t12 = R1.*t3;
t13 = R2.*t3;
t18 = t4.^2;
t19 = t5.^2;
t20 = -t18;
t21 = -t19;
t22 = t10+t17+y;
t23 = t11+t16+yo;
t24 = t12+t14+xo;
t25 = t13+t15+x;
t26 = t22.^2;
t27 = t23.^2;
t28 = t24.^2;
t29 = t25.^2;
t30 = t20+t26+t28;
t31 = t21+t27+t29;
Lfl12 = V.*t2.*(t30.*(t6-t7+t13.*2.0)-t31.*(-t6+t7+t12.*2.0))-V.*t3.*(t30.*(-t8+t9+t11.*2.0)-t31.*(t8-t9+t10.*2.0));
