function Lgl12 = Lgl12_gen(x,y,theta,V,R1,R2,xo,yo,d)
%LGL12_GEN
%    LGL12 = LGL12_GEN(X,Y,THETA,V,R1,R2,XO,YO,D)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Aug-2020 16:20:29

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.*x;
t5 = t2.*xo;
t6 = t3.*y;
t7 = t3.*yo;
t8 = -t5;
t9 = -t7;
t10 = t4+t6+t8+t9;
Lgl12 = R2.*t10.*((-x+xo+R1.*t3).^2+(y-yo+R1.*t2).^2-(R1+d).^2).*2.0-R1.*t10.*((x-xo+R2.*t3).^2+(-y+yo+R2.*t2).^2-(R2+d).^2).*2.0;
