function LgLyap = LgLyap(x,y,theta,xd,yd)
%LGLYAP
%    LGLYAP = LGLYAP(X,Y,THETA,XD,YD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Aug-2020 22:37:21

t2 = cos(theta);
t3 = sin(theta);
t4 = -xd;
t5 = -yd;
t6 = t4+x;
t7 = t5+y;
LgLyap = (t2.*t6+t3.*t7).*(t2.*t7-t3.*t6).*-2.0;
