function lyapFun = lyapFun(x,y,theta,xd,yd)
%LYAPFUN
%    LYAPFUN = LYAPFUN(X,Y,THETA,XD,YD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Aug-2020 22:37:21

lyapFun = (cos(theta).*(y-yd)-sin(theta).*(x-xd)).^2;
